name: Test

on: [ workflow_dispatch ]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Download Go tip
        uses: robinraju/release-downloader@v1.8
        with:
          tag: "${{ matrix.platform }}"
          fileName: go.zip
      - name: Install Go tip
        run: |
          set -x
          unzip go.zip -d $HOME/sdk
          echo "GOROOT=$HOME/sdk/gotip" >> "$GITHUB_ENV"
          echo "GOPATH=$HOME/go" >> "$GITHUB_ENV"
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          echo "$HOME/sdk/gotip/bin" >> "$GITHUB_PATH"
      - name: Test Go
        run: |
          set -x
          which go
          go version